/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GpHEzSoPbbK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function AddWorkshop() {
  return (
    <Card className="w-1/3 mx-auto">
      <CardHeader>
        <CardTitle>Arrange a Workshop</CardTitle>
        <CardDescription>Fill out the details to create a new workshop.</CardDescription>
      </CardHeader>
      <CardContent>
        <form className="grid gap-4">
          <div className="grid gap-2">
            <Label htmlFor="title">Title</Label>
            <Input id="title" placeholder="Enter workshop title" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="description">Description</Label>
            <Textarea id="description" rows={4} placeholder="Provide a description for the workshop" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="thumbnail">Thumbnail</Label>
            <Input id="thumbnail" type="file" />
          </div>
          <div className="space-y-2">
          <Label htmlFor="dropLink">Set workshop token</Label>
          <Input id="dropLink" placeholder="Enter the course drop link" />
        </div>
          <Button type="submit" className="mt-4 font-semibold">
            Submit
          </Button>
        </form>
      </CardContent>
    </Card>
  )
}
