/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zCEoryG59Oa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function AddCourse() {
  return (
    <Card className="w-1/3 mx-auto">
      <CardHeader>
        <CardTitle>Add New Course</CardTitle>
        <CardDescription>Fill out the details below to create a new course.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="title">Course Title</Label>
          <Input id="title" placeholder="Enter course title" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="description">Course Description</Label>
          <Textarea id="description" rows={4} placeholder="Provide a brief description of the course" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="dropLink">Course Drop Link</Label>
          <Input id="dropLink" placeholder="Enter the course drop link" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="dropLink">Set course token</Label>
          <Input id="dropLink" placeholder="Enter the course drop link" />
        </div>
      </CardContent>
      <CardFooter className="flex justify-end">
        <Button type="submit">Submit</Button>
      </CardFooter>
    </Card>
  )
}
