/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EDDOflcF0u8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Syne } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"

export function PurposeDao() {
  return (
    <div className="flex flex-col  w-full pt-10">
      <main className="flex-1 bg-background">
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container px-4 md:px-6">
            <div className="bg-card rounded-lg shadow-sm p-6 md:p-8 lg:p-10">
              <h2 className="text-2xl font-bold mb-4">Submit a New Proposal</h2>
              <form className="space-y-4">
                <div>
                  <Label htmlFor="title">Proposal Title</Label>
                  <Input id="title" placeholder="Enter proposal title" />
                </div>
                <div>
                  <Label htmlFor="description">Proposal Description</Label>
                  <Textarea id="description" placeholder="Enter proposal description" rows={4} />
                </div>
                
                <Button type="submit">Submit Proposal</Button>
              </form>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20 bg-muted">
          <div className="container px-4 md:px-6">
            <h2 className="text-2xl font-bold mb-6">Current Proposals</h2>
            <div className="grid gap-6">
              <Card>
                <CardHeader>
                  <CardTitle>Improve DAO Governance</CardTitle>
                  <CardDescription>
                    Proposal to implement new voting mechanisms and decision-making processes.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Badge variant="secondary">Governance</Badge>
                      <span className="text-muted-foreground text-sm">Proposed 2 days ago</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Button variant="outline" size="sm">
                        Vote
                      </Button>
                      <Button variant="outline" size="sm">
                        View
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Increase DAO Treasury Funding</CardTitle>
                  <CardDescription>
                    Proposal to allocate more funds to the DAO treasury for future initiatives.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Badge variant="secondary">Finance</Badge>
                      <span className="text-muted-foreground text-sm">Proposed 5 days ago</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Button variant="outline" size="sm">
                        Vote
                      </Button>
                      <Button variant="outline" size="sm">
                        View
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Expand Community Outreach</CardTitle>
                  <CardDescription>
                    Proposal to increase marketing and community engagement initiatives.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Badge variant="secondary">Community</Badge>
                      <span className="text-muted-foreground text-sm">Proposed 1 week ago</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Button variant="outline" size="sm">
                        Vote
                      </Button>
                      <Button variant="outline" size="sm">
                        View
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted p-6 md:py-8 w-full">
        <div className="container max-w-7xl flex items-center justify-between">
          <p className="text-muted-foreground text-sm">&copy; 2024 Acme DAO. All rights reserved.</p>
          <nav className="flex gap-4 sm:gap-6">
            <Link
              href="#"
              className="text-muted-foreground text-sm hover:underline underline-offset-4"
              prefetch={false}
            >
              Terms of Service
            </Link>
            <Link
              href="#"
              className="text-muted-foreground text-sm hover:underline underline-offset-4"
              prefetch={false}
            >
              Privacy Policy
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}
