import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import AnonAdhaar from "@/components/anonAdhaarProvider"
// import { UniDaoProvider } from "@/components/UniDaoProvider";
import {ThirdwebClientProvider} from "@/components/ThirdWebProvider"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  weight: "300",
  variable: "--font-poppins-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.className} dark`}>
        <ThirdwebClientProvider>
        {/* <UniDaoProvider> */}
        <AnonAdhaar>
          {children}
        </AnonAdhaar>
        {/* </UniDaoProvider> */}
        </ThirdwebClientProvider>
      </body>
    </html>
  );
}
